### ISSUE TITLE
Non-minified files?

### ISSUE THREAD

**Issue by stephenplusplus** [GetAmbassador/conventions-bower#106]
Hello! I was just stopping by to check out the code but found only minified files. The [Bower spec](http://bower.io/docs/creating-packages/#main) says to ship un-minified code, leaving it up to the user's build process to handle minification if they want it.

**Comment by chaselee** [comment]
Hey @stephenplusplus! There's a whole private repo sitting behind this bower package. We're hoping to truly open source various components in the future, but for right now we're just using this internally until that time comes. Coming to the [meetup](http://www.meetup.com/ng-Detroit/events/224936093/) tonight?

**Comment by stephenplusplus** [comment]
No problem, don't mind me. I just have the tendency to feel left out when I see minified code!

And also, unfortunately not :( I wish I could, but I heard about it too late. I'll stay tuned for the next one so me and my buddy @callmehiphop can join!

**Comment by chaselee** [comment]
We'd definitely love to deliver un-minified code. Stay tuned!

Darn, looking forward to seeing you at the next one then!
