### ISSUE TITLE
Release v0.11.4

### ISSUE THREAD

**Issue by Chochek** [GetAmbassador/conventions-bower#110]
This release will include:
- [x] fix table get request with page 0
- [x] improved table performance
- [x] new proportion ring styles

**Comment by Chochek** [comment]
### Spec

- [x] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.11.4
- [x] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.11.4
- [x] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.11.4

0 points

**Comment by Chochek** [comment]
@gpszymczak please review spec

**Comment by gpszymczak** [comment]
:+1:

**Comment by Chochek** [comment]
### Review Plan

- [ ] Code is updated
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/bbfe9bfc7b0464a39f4c6ee8ee84f52c2ee2bccd/bower.json#L3) has updated version v0.11.3

**Comment by Chochek** [comment]
@jivinivan please review

**Comment by jivinivan** [comment]
Reviewing

**Comment by jivinivan** [comment]
:+1:

**Comment by Chochek** [comment]
### QA plan

- [ ] [Releases](https://github.com/GetAmbassador/conventions-bower/releases) contains v0.11.4
- [ ] [bower.json](https://github.com/GetAmbassador/conventions-bower/blob/master/bower.json#L3) has updated version v0.11.4
- [ ] [Ambassador conventions](https://github.com/GetAmbassador/ambassador-conventions/releases) releases contains v0.11.4

**Comment by Chochek** [comment]
@gpszymczak please QA

**Comment by gpszymczak** [comment]
QAing
